import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layouts/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IT Service Desk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="mt-10">{children}</div>
      </body>
    </html>
  );
}
